FLASK_APP='app2.py'
FLASK_ENV='production'
SQLALCHEMY_DATABASE_URI='sqlite:///db.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS=True
DEBUG= False

OAUTH2_JWT_ENABLED = True
OAUTH2_JWT_ISS = 'https://donelogin.ai'
OAUTH2_JWT_KEY = 'secret-key'
OAUTH2_JWT_ALG = 'HS256'

PERMANENT_SESSION_LIFETIME = 1800
